"""phase1 rights sources campaigns money ledger

Revision ID: bb48ccaa9549
Revises: f9f9d995b169
Create Date: 2026-08-25 12:23:44.157245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb48ccaa9549'
down_revision: Union[str, Sequence[str], None] = 'f9f9d995b169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('commission_inr', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_costs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('task_class', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('clip_id', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('rate_per_1k', sa.Float(), nullable=False),
    sa.Column('pool_size', sa.Float(), nullable=False),
    sa.Column('pool_remaining', sa.Float(), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('brief_url', sa.String(), nullable=True),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('required_tags', sa.JSON(), nullable=True),
    sa.Column('banned_claims', sa.JSON(), nullable=True),
    sa.Column('per_clip_cap', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('effective_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_status_pool_remaining', ['status', 'pool_remaining'], unique=False)

    op.create_table('identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('niche', sa.String(), nullable=True),
    sa.Column('caption_style_set', sa.JSON(), nullable=True),
    sa.Column('cover_layout', sa.String(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('music_bed_set', sa.JSON(), nullable=True),
    sa.Column('posting_rhythm', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('token_ref', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('monetization_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('transcript_cached', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_publication_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('channel_source', sa.String(), nullable=True),
    sa.Column('contact_ref', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('deal_value_inr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_costs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('publication_id', sa.String(), nullable=True),
    sa.Column('clip_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('currency_orig', sa.String(), nullable=True),
    sa.Column('amount_orig', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_events', schema=None) as batch_op:
        batch_op.create_index('ix_revenue_events_clip_id_occurred_at', ['clip_id', 'occurred_at'], unique=False)

    op.create_table('rights_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('evidence_path', sa.String(), nullable=False),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rights_records')
    with op.batch_alter_table('revenue_events', schema=None) as batch_op:
        batch_op.drop_index('ix_revenue_events_clip_id_occurred_at')

    op.drop_table('revenue_events')
    op.drop_table('production_costs')
    op.drop_table('leads')
    op.drop_table('sources')
    op.drop_table('platform_accounts')
    op.drop_table('identities')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status_pool_remaining')

    op.drop_table('campaigns')
    op.drop_table('api_costs')
    op.drop_table('affiliate_links')
    # ### end Alembic commands ###
